---
displayName: Golang Serverless App Stack
description: Stack for developing a Golang Function
tags: ["Golang", "Serverless", "Function"]
version: 0.0.1
repository:
  url: https://github.com/sbose78/golang-function
  ref: "8b79fbc"