---
displayName: Quarkus Serverless App Stack
description: Stack for developing Quarkus Function
tags: ["Quarkus", "Serverless", "Function"]
version: 0.0.1

# outer loop information
deploy:
  components:
    - build: 
        - build/Dockerfile
      deploy: 
        - manifests/deploy.yaml