---
displayName: Multi-service Fuse Springboot Stack
description: Stack for developing multi-service Springboot Apps
tags: ["Springboot", "Fuse", "Circuitbreaker"]
version: 0.0.1
repository:
  url: https://github.com/sbose78/fuse-springboot-circuit-breaker-booster
  ref: "3924503"
